DROP TRIGGER IF EXISTS enforce_passkey_limit;
DROP INDEX IF EXISTS idx_cpr_hash;
DROP INDEX IF EXISTS idx_passkeys_credential_id;
DROP INDEX IF EXISTS idx_passkeys_account_id;
DROP TABLE IF EXISTS account_roles;
DROP TABLE IF EXISTS totp_secrets;
DROP TABLE IF EXISTS passkeys;
DROP TABLE IF EXISTS cpr_data;
DROP TABLE IF EXISTS accounts;
